env:
  browser: true
  commonjs: true
  es6: true
plugins:
  - destructuring
extends: 'plugin:destructuring/recommended'
parserOptions:
  sourceType: module
globals:
  ENV: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  comma-style:
    - 2
    - last
